#include "thermal_camera.h"
#include "MLX/MLX90640_API.h"
#include "zephyr/drivers/i2c.h"
#include "zephyr/kernel.h"
#include "zephyr/kernel/thread.h"
#include "zephyr/logging/log.h"
#include <cstdint>
#include <cstdio>
#include <algorithm>

LOG_MODULE_REGISTER(ThermalCamera);

K_THREAD_STACK_DEFINE(upFrameStack, CAMERA_THREAD_STACK_SIZE);

ThermalCamera::ThermalCamera()
{
    k_mutex_init(&frameMutex_);
    k_sem_init(&frameReadySem_, 0, 1);
}

int ThermalCamera::init()
{

    
    sensor_init_timestamp_S = k_uptime_get() / 1000;

    static uint16_t eeMLX90640[832];

    int status{};

    status = MLX90640_DumpEE(MLX906040_I2C_ADRR, eeMLX90640);

    status = MLX90640_ExtractParameters(eeMLX90640, &params);

    if (status != 0)
    {
        LOG_ERR("Extracting Params Failed %d", status);
        return status;
    }

    running_ = true;

    upFrameThreadPtr = k_thread_create(&upFrameThread, upFrameStack, CAPTURE_THREAD_STACK_SIZE, updateFrameThreadEntry,
                                       this, nullptr, nullptr, CAPTURE_THREAD_PRIORITY, 0, K_NO_WAIT);

    LOG_INF("Thermal Camera Initalized");
    return 0;
}

bool ThermalCamera::isWarm(void)
{
    int64_t elapsed_ms = (k_uptime_get() / 1000) - sensor_init_timestamp_S;
    return elapsed_ms >= MLX90640_WARMUP_S;
}

void ThermalCamera::updateFrameThreadEntry(void *p1, void *p2, void *p3)
{

    static_cast<ThermalCamera *>(p1)->updateFrame();
    // pass the thermalCamera object pointer to P1 for entry so that updateFrame can be called while being a non static
    // class member
}

/**
 * @brief Calculates the temperature and updates the ThermalFrame struct
 *
 * @param outFrame
 * @return int
 */
int ThermalCamera::getFrame(ThermalFrame &outFrame)
{

    float emissivity = 0.95;
    float trShift{8};
    float tr{};
    // TODO: These calibration constants are dependent on the emissivity of the surroundings
    //       and the temperature shift caused by the emissivity of the surroundings
    //       THESE ARE DEFAULT VALUES (should also probably class members)

    int status;

    static uint16_t mlx90640Frame[TOTAL_FRAME_BUFF_AMT];

    status = MLX90640_GetFrameData(MLX906040_I2C_ADRR, mlx90640Frame);

    if (status < 0)
    {
        LOG_ERR("GetFrameData failed: %d", status);
        return status;
    }

    outFrame.subPage = status;

    tr = MLX90640_GetTa(mlx90640Frame, &params) - trShift;

    MLX90640_CalculateTo(mlx90640Frame, &params, emissivity, tr, (float *)outFrame.pixels);
    // My guess is that this has no return since it doest handle I2C communication.
}

/**
 * @brief the threading loop
 *
 * @return int
 */
int ThermalCamera::updateFrame()
{

    while (running_)
    {

        getFrame(*internalFramePtr);

        internalFramePtr->frameId = nextFrameId_;
        nextFrameId_++;
        internalFramePtr->warmedData = isWarm();

        k_mutex_lock(&frameMutex_, K_FOREVER);
        std::swap(externFramePtr, internalFramePtr);
        k_mutex_unlock(&frameMutex_);

        k_sem_give(&frameReadySem_);
    }

    return 0;
    // TODO Implement some sort of error handling.
    // TODO: implement variable wait times to save cpu time we know frames wont be updated based on the refresh rate of
    // the
}

// FULLY generated by claude
void ThermalCamera::logFrame(ThermalFrame &frame)
{

    LOG_INF("=== Frame %u | subpage %u | warmed: %d ===", frame.frameId, frame.subPage, (int)frame.warmedData);

    // Each pixel formatted as "XXX.X " = 6 chars, 24 cols per row
    char rowBuf[FRAME_COLS * 6 + 1];

    for (int row = 0; row < FRAME_ROWS; row++)
    {
        int offset = 0;
        for (int col = 0; col < FRAME_COLS; col++)
        {
            float t = frame.pixels[row * FRAME_COLS + col];
            int whole = (int)t;
            int frac = (int)((t - (float)whole) * 10);
            if (frac < 0)
            {
                frac = -frac;
            }
            offset += snprintf(rowBuf + offset, sizeof(rowBuf) - offset, "%3d.%d ", whole, frac);
        }
        LOG_INF("R%02d: %s", row, rowBuf);
    }
}

int ThermalCamera::close()
{

    if (!running_ && upFrameThreadPtr == nullptr)
    {

        LOG_DBG("Tried Ending process without initializing");
        return 0; // TODO: should this be an error code?
    }

    running_ = false;

    k_thread_abort(upFrameThreadPtr);

    k_thread_join(upFrameThreadPtr, K_FOREVER);
}



ThermalFrame* ThermalCamera::getUpdatedFrame(){


    int ret = k_sem_take(&frameReadySem_, K_NO_WAIT);
    if(ret != 0 ){
        return nullptr;
    }

    k_mutex_lock(&frameMutex_, K_FOREVER);
    ThermalFrame *safePtr = externFramePtr;
    k_mutex_unlock(&frameMutex_);


    return safePtr;

}